### ISSUE TITLE
Stroke width of outline icons is too thin

### ISSUE THREAD

**Issue by lemonad** [amoutonbrady/solid-heroicons#4]
In version 0.8.0, the stroke width was 2 like it should be according to heroicons.com
> Outline: 2px stroke weight, 24x24 bounding box

Comparing e.g. the `adjustments` icon in `outline/index.js` on 0.8.0:

```
export const adjustments = { path: `<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6V4m0 2a2 2 0 100 4m0-4a2 2 0 110 4m-6 8a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4m6 6v10m6-2a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4"/>`, outline: true };
```

vs. in `outline.index.jsx` on 2.0.1:

```
export const adjustments = { path: <><path stroke-linecap="round" stroke-linejoin="round" d="M12 6V4m0 2a2 2 0 100 4m0-4a2 2 0 110 4m-6 8a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4m6 6v10m6-2a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4"/></>, outline: true };
```

**Comment by ShivamJoker** [comment]
same here the author seems to have abandoned this lib

**Comment by amoutonbrady** [comment]
Hi, I did not abandon the package. Time is just hard to find.

I'm using the package almost everyday professionally.

I'll look into it :)
