### ISSUE TITLE
The 2.0.1 release only renders icons in the last instance of a component?

### ISSUE THREAD

**Issue by lemonad** [amoutonbrady/solid-heroicons#5]
I'm using two different components, one with the `adjustments` icon and one with the `beaker` icon. The icons seem to only render for the last instance of each component:

<img width="364" alt="image" src="https://user-images.githubusercontent.com/56049/158053820-0687ad96-ff24-4f53-b9b4-75e2c3d7c073.png">

When changing both to use the `beaker` icon, this is the result:

<img width="364" alt="image" src="https://user-images.githubusercontent.com/56049/158053841-a2a3a401-104e-43e5-9e84-d8322bc93c56.png">

This is the code I use within each component
```
import { Icon } from "solid-heroicons";
import { adjustments, beaker } from "solid-heroicons/outline";

...
<Icon
  class="h-3.5 inline-block ml-0.5 opacity-80 -rotate-12 transform"
  path={beaker}
/>
```

When using version 1.2.1 and earlier, everything looks fine:

<img width="356" alt="image" src="https://user-images.githubusercontent.com/56049/158054011-6a2fff2f-b328-4305-8ffe-d38c0d6b7595.png">

**Comment by amoutonbrady** [comment]
Hi, sorry for the long delay. I think this has been brought up on the Discord at the time.

It was related to work around making the lib SSR friendly and was fixed later on in a release :)

Here's a showcase of it working : https://stackblitz.com/edit/github-u6jpit?file=src/index.css

**Comment by lemonad** [comment]
Thanks, @amoutonbrady! I'll update to the latest version now : )
