### ISSUE TITLE
Upgrade to rollup 3

### ISSUE THREAD

**Issue by amoutonbrady** [amoutonbrady/solid-heroicons#7]
I tried to upgrade to rollup 3 and its plugins but it appears that somehow that doesn't work.
I'll try to tackle that when I have the time but if anyone wants to contribute that would be lovely!

**Comment by MaverickDe** [comment]
is the issue assigned to anyone?

**Comment by amoutonbrady** [comment]
@MaverickDe no, it's not :)

Would you like to give it a shot?

**Comment by MaverickDe** [comment]
Yeah I would love to. But I would want  in-depth explanation about the issue

**Comment by amoutonbrady** [comment]
Sure! So basically what you have to do is run the following command: 
- Be on node@19 (although I suspect lower version of nodes probably produce the same outcome)
- `pnpm up -Li` which will ask you which dependencies you want to upgrade
- Select rollup 3+ and its plugin
- Run `pnpm build` and it should yell at you about `rollup-preset-solid` not being a module or something like that :)

Hope that helps!
