### ISSUE TITLE
HeroIcon version

### ISSUE THREAD

**Issue by awhitford** [amoutonbrady/solid-heroicons#9]
Is there a way to tell when this was last generated?  Version 2.0.17, for example, has was released March 30th:
<img width="440" alt="image" src="https://user-images.githubusercontent.com/123887/236796861-adbb61a8-27fc-4296-a5d2-31b06f315375.png">
However I can see [here](https://github.com/tailwindlabs/heroicons/tree/master/src/24/outline) that the latest src is about 9 months ago...  (Aug 23, 2022). 

When was this last package generated?  Is it complete with v2?

**Comment by amoutonbrady** [comment]
Hey! I try to re-generate the repo as often as I can (which you can tell by the git history, isn't as much as I would like to unfortunately).

I'll re-generate them and publish a new version.

Thanks
